services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Lle\EntityFileBundle\Service\EntityFileManager:
        arguments:
            - '@parameter_bag'
            - !tagged_locator { tag: 'flysystem.storage' }
            - '@property_accessor'
