services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true


    Lle\EntityFileBundle\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    Lle\EntityFileBundle\Service\EntityFileLoader:
        arguments:
            - '@parameter_bag'
            - !tagged_locator { tag: 'flysystem.storage' }
            - '@doctrine.orm.entity_manager'
            - '@router.default'
